# Generated by Django 5.2.5 on 2025-09-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
