# Generated by Django 5.2.5 on 2025-11-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
