# Generated by Django 5.2.6 on 2025-10-14 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex'), ('K', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(49)]),
        ),
        migrations.AlterField(
            model_name='shoevariant',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
