# Generated by Django 5.2.6 on 2025-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_shoe_color_remove_shoe_size_alter_shoe_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('casual', 'Casual'), ('formal', 'Formal'), ('sports', 'Sports'), ('sneakers', 'Sneakers'), ('boots', 'Boots'), ('sandals', 'Sandals'), ('loafers', 'Loafers'), ('athletic', 'Athletic')], max_length=50),
        ),
    ]
