# Generated by Django 5.2.6 on 2025-10-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_order_status_alter_shoe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoevariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
