# Generated by Django 5.2.6 on 2025-10-15 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_shoevariant_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='shoe_variants',
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
