# Generated by Django 5.2.6 on 2025-10-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_items_order_shoe_variants_review_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image_url',
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoe_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.shoe')),
            ],
        ),
    ]
