# Generated by Django 5.2.7 on 2025-10-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_items_order_shoe_variants_review_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('running', 'Running'), ('sports', 'Sports'), ('casual', 'Casual'), ('sneakers', 'Sneakers'), ('athletic', 'Athletic'), ('formal', 'Formal'), ('loafers', 'Loafers'), ('crocs', 'Crocs'), ('heels', 'Heels'), ('dress pumps', 'Dress pumps'), ('boots', 'Boots'), ('sandals', 'Sandals')], max_length=50),
        ),
    ]
